#!/bin/bash

function venv () {
    source "$1/bin/activate"
}

function gic () {
    git commit -m "$1" 
}

function tma () {
    tmux a -t "$1"
}

function dex () {
    docker exec -ti "$1" bash
}

extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"     ;;
            *.tar.gz)    tar xzf "$1"     ;;
            *.bz2)       bunzip2 "$1"     ;;
            *.rar)       unrar e "$1"     ;;
            *.gz)        gunzip "$1"      ;;
            *.tar)       tar xf "$1"      ;;
            *.tbz2)      tar xjf "$1"     ;;
            *.tgz)       tar xzf "$1"     ;;
            *.zip)       unzip "$1"       ;;
            *.Z)         uncompress "$1"  ;;
            *.7z)        7z x "$1"        ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Enhanced aliases
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias lt='ls -lahtr --color=auto'  # List by time, reversed
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias now='date +"%T"'
alias today='date +"%d-%m-%Y"'

# File search
alias ff='find . -type f -name'
alias fd='find . -type d -name'

alias ll='ls -lAh'
alias sudo='sudo '
alias gis='git status'
alias gip='git pull'
alias gid='git diff'
alias giau='git add -u'
alias tmls='tmux ls'
alias tmcp='tmux show-buffer | xclip -selection clipboard'
alias dps='docker ps'
alias python='python3'
# alias nvim='venv ~/.venvs/nvim && nvim'
alias rsyncd='rsync -auh --info=progress2'
alias clip='xclip -selection clipboard'
alias pipr='pip install -r requirements.txt'
