set -g default-terminal "screen-256color"
set -g mouse on
set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

unbind C-b
unbind C-w
set-option -g prefix C-Space
bind-key C-Space send-prefix
bind-key -n C-w select-pane -R

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Keep at the bottom
run '~/.tmux/plugins/tpm/tpm'
